version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: python app.py 
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mynetwork

networks:
  mynetwork:
